language: python
sudo: false
python:
  - 2.7
  - 2.6
addons:
  apt:
    packages:
    - ccache
    - swig
cache:
  - pip
  - ccache
install:
  - pip install --upgrade pip
  - pip install cython
  - pip install -r travis-ci-requirements.txt
  - python setup.py develop
  # there is a circular dependency with codetools
  - pip install git+http://github.com/enthought/blockcanvas.git#egg=blockcanvas
script:
  - coverage run -m nose.core -v
after_success:
  - pip instal codecov
  - codecov
