language: python
sudo: false
python:
  - 2.7
  - 2.6
  - 3.4
addons:
  apt:
    packages:
    - ccache
    - swig
matrix:
 allow_failures:
    - python: 3.4
cache:
  - pip
  - ccache
install:
  - pip install --upgrade pip
  - pip install cython
  - pip install -r travis-ci-requirements.txt
  - python setup.py develop
  # there is a circular dependency with codetools
  - pip install git+http://github.com/enthought/blockcanvas.git#egg=blockcanvas
before_script:
  - cd integrationtests
  - cp .coveragerc integrationtests/
script:
  - coverage run -m nose.core -v
  # Do not run the integration tests (see issue #21)
  # - coverage run -a -m nose.core integrationtests/ -v
after_success:
  - pip instal codecov
  - codecov
